name: example
description: An example of the service_isolate

environment:
  sdk: '>=3.2.0-0 <4.0.0'

dependencies:
  protobuf: ^2.0.0
  service_isolate: any
  protoc_builder: ^0.4.0
  # protoc_builder:
  #  git: https://github.com/ewaters/dart-protoc-builder.git

dev_dependencies:
  build_runner: ^2.1.5
  lints: ^1.0.0
  test: any

dependency_overrides:
  service_isolate:
    path: ../
