name: service_isolate
description: A protobuf-based service isolate
publish: none

environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies:
  protobuf: ^2.0.0

dev_dependencies:
  build_runner: ^2.1.5
  lints: ^1.0.0
  stream_channel: ^2.1.0
  protoc_builder: any

dependency_overrides:
  protoc_builder:
    path: ../dart-protoc-builder/
